### ISSUE TITLE
Android Basics: first-kotlin-program

### ISSUE THREAD

**Issue by conantopro** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#152] opened 2021-11-13 22:09 UTC
Hello,

Why do I get an error when I run the Kotlin Playground sample program?

Exception in thread "main" java.io.FileNotFoundException: /var/task/tmp/70f9d41fda8a4a1f991cc85ebdacbbff/executor.policy (No such file or directory)
 at java.io.FileOutputStream.open0 (FileOutputStream.java:-2) 
 at java.io.FileOutputStream.open (FileOutputStream.java:270) 
 at java.io.FileOutputStream.<init> (FileOutputStream.java:213) 

![kotlin-playground-error](https://user-images.githubusercontent.com/88296978/141660426-aadff6d6-c1a4-46bd-b022-9c99da5db2eb.png)

**Comment by osuleymanova** [comment] 2022-08-01 18:09
@conantopro 
Thank you for reaching out to us. Please let us know if you still facing this issue.

**Comment by osuleymanova** [comment] 2023-04-03 21:19
The issue is closed as not reproducible:
![Screenshot 2023-04-03 at 2 16 50 PM](https://user-images.githubusercontent.com/86437155/229629630-f112433f-dc81-40ef-b5ae-66dc5a7f9388.png)
It was probably a one-time system glitch.

**Closed by osuleymanova** 2023-04-03 21:19 UTC
