### ISSUE TITLE
Android Basics: kotlin-birthday-message

### ISSUE THREAD

**Issue by tonylf** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#44] opened 2021-04-17 09:15 UTC
In Create a birthday message in Kotlin / 4. Print a birthday banner with a border, in one of the instructions, the "`" is interpreted as the closing tag instead of content
<img width="406" alt="Capture d’écran 2021-04-17 à 11 14 35" src="https://user-images.githubusercontent.com/47084640/115107972-389d8b80-9f6e-11eb-813c-05e8feb646be.png">

**Comment by ashnohe** [comment] 2021-11-01 23:17
Duplicate of #113

**Closed by ashnohe** 2021-11-01 23:17 UTC
