### ISSUE TITLE
Android Basics: install-android-studio

### ISSUE THREAD

**Issue by Gonalfus** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#115] opened 2021-11-02 13:19 UTC
**https://developer.android.com/studio.

**In which task and step of the codelab can this issue be found?** I think in the download button

**Hello,
It does not allow me to download Android Studios. I click and it does not appear to see the license.

I hope you can help me. Thank you

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by ashnohe** [comment] 2021-11-02 21:05
Thanks @Gonalfus for flagging this issue. I believe this is a duplicate of issue #110 and I've reported this issue to the developer relations community.

As a workaround, if possible you might download Android Studio from the English page, where the terms and conditions do appear.

**Comment by ashnohe** [comment] 2021-11-03 15:34
This issue appears to have been resolved. Let us know if that's not the case for you. Thanks!

**Closed by ashnohe** 2021-11-03 15:34 UTC
Labels: bug, duplicate, help wanted, In progress
