### ISSUE TITLE
Android Basics: install-android-studio

### ISSUE THREAD

**Issue by JansenTanu** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#32] opened 2021-03-27 17:39 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-install-android-studio?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-two%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-install-android-studio#4

**In which task and step of the codelab can this issue be found?**
on task 5, step 6 on instruction to install android studio for windows.

**Describe the problem**
I think some image is missing.....

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by ashnohe** [comment] 2021-11-01 22:41
Duplicate of #27

**Closed by ashnohe** 2021-11-01 22:41 UTC
