### ISSUE TITLE
Android Basics: first-template-project

### ISSUE THREAD

**Issue by korak1111** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#60] opened 2021-06-04 17:51 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-first-template-project?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-two%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-first-template-project#2

**In which task and step of the codelab can this issue be found?**
Task 3 item 2

**Describe the problem**

The image (93848e9822710c69.png) and text are not spaced correctly.

**Steps to reproduce?**
1. Go to...
https://developer.android.com/codelabs/basic-android-kotlin-training-first-template-project?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-two%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-first-template-project#2
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by ashnohe** [comment] 2021-11-02 17:40
Duplicate of #35

**Closed by ashnohe** 2021-11-02 17:40 UTC
