### ISSUE TITLE
Android Basics: first-kotlin-program

### ISSUE THREAD

**Issue by kactukx** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#154] opened 2021-11-14 01:30 UTC
![image](https://user-images.githubusercontent.com/94265699/141664084-e4523481-3755-44aa-a621-2fc4e8769371.png)
HI, I GOT A PROBLEM WITH THIS, ANYONE CAN HELP ME?

**Comment by osuleymanova** [comment] 2022-08-01 18:06
Duplicate of #153, #152

**Comment by osuleymanova** [comment] 2023-04-03 21:21
The issue is closed as not reproducible:
![Screenshot 2023-04-03 at 2 16 50 PM](https://user-images.githubusercontent.com/86437155/229629630-f112433f-dc81-40ef-b5ae-66dc5a7f9388.png)
It was probably a one-time system glitch.

**Closed by osuleymanova** 2023-04-03 21:21 UTC
