### ISSUE TITLE
Android Basics: first-template-project

### ISSUE THREAD

**Issue by w-farah** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#57] opened 2021-05-25 19:13 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-first-template-project?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-two%3Fhl%3Den%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-first-template-project&hl=en#1

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

we are now using 4.2, not 4.0. some visual differences that may trip up users

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 4.2
_API version of the emulator:_ 4.0

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by ashnohe** [comment] 2021-11-02 18:53
Duplicate of #40

**Closed by ashnohe** 2021-11-02 18:53 UTC
Labels: Formatting issue on DAC
