### ISSUE TITLE
Android Basics: first-template-project

### ISSUE THREAD

**Issue by reknoZ** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#77] opened 2021-07-23 20:00 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-first-template-project

**In which task and step of the codelab can this issue be found?**
Step 3

**Describe the problem**
"Click the tabs at the top...."

It's now on the side. And the image for Android Studio has changed.

**Steps to reproduce?**
n/a

**Versions**
_Android Studio version:_ 4.2.2
_API version of the emulator:_ n/a

**Additional information**

**Comment by ashnohe** [comment] 2021-11-02 18:53
Duplicate of #40

**Closed by ashnohe** 2021-11-02 18:53 UTC
Labels: Formatting issue on DAC
