### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by martinvisintini** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#135] opened 2021-11-12 17:45 UTC
[**URL of codelab**](https://developer.android.com/training/kotlinplayground)

just the start

I can´t use the Kotlin playground, not even the "hello world", I get an error message:

Exception in thread "main" java.io.FileNotFoundException: /var/task/tmp/495b6e84cc75478092078bd36abca820/executor.policy (No such file or directory)
 at java.io.FileOutputStream.open0 (FileOutputStream.java:-2) 
 at java.io.FileOutputStream.open (FileOutputStream.java:270) 
 at java.io.FileOutputStream.<init> (FileOutputStream.java:213) 

**Steps to reproduce?**
1. [Go to...](https://developer.android.com/training/kotlinplayground)
2. click on: Play
3. See error...: Exception in thread "main" java.io.FileNotFoundException: /var/task/tmp/495b6e84cc75478092078bd36abca820/executor.policy (No such file or directory)
 at java.io.FileOutputStream.open0 (FileOutputStream.java:-2) 
 at java.io.FileOutputStream.open (FileOutputStream.java:270) 
 at java.io.FileOutputStream.<init> (FileOutputStream.java:213) 

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by martinvisintini** [comment] 2021-11-12 17:46
![imagen](https://user-images.githubusercontent.com/94192369/141511626-00bd3e4d-8468-40f6-8aa3-a7955e79c8f6.png)

**Comment by osuleymanova** [comment] 2022-08-01 18:38
Duplicate of #152, #153, #154

**Comment by osuleymanova** [comment] 2023-04-03 21:21
The issue is closed as not reproducible:
![Screenshot 2023-04-03 at 2 16 50 PM](https://user-images.githubusercontent.com/86437155/229629630-f112433f-dc81-40ef-b5ae-66dc5a7f9388.png)
It was probably a one-time system glitch.

**Closed by osuleymanova** 2023-04-03 21:21 UTC
