### ISSUE TITLE
Android Basics: Done button missing - birthday-card-app

### ISSUE THREAD

**Issue by tusharsrivastava2904** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#5] opened 2020-11-27 14:13 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-birthday-card-app#6

**In which task and step of the codelab can this issue be found?**
Next button Missing on part 7

**Describe the problem**

Next button to the next pathway is missing

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by ashnohe** [comment] 2021-11-01 21:14
Duplicate of #1

**Closed by ashnohe** 2021-11-01 21:14 UTC
Labels: Formatting issue on DAC
