### ISSUE TITLE
Android Basics: first-kotlin-program

### ISSUE THREAD

**Issue by nhveliz** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#156] opened 2021-11-14 03:40 UTC
Hola! Cada vez que quiero correr un simple println("Hello world") ocurre este error...

Exception in thread "main" java.io.FileNotFoundException: /var/task/tmp/611165d443504336abcd9a9c24adda5a/executor.policy (No such file or directory)
 at java.io.FileOutputStream.open0 (FileOutputStream.java:-2) 
 at java.io.FileOutputStream.open (FileOutputStream.java:270) 
 at java.io.FileOutputStream.<init> (FileOutputStream.java:213)

Como soluciono esto para poder seguir con el curso??

**Comment by osuleymanova** [comment] 2022-08-01 18:07
Duplicate of #154, #153, #152

**Comment by osuleymanova** [comment] 2022-08-01 18:10
@nhveliz 
Thank you for reaching out to us. Please let us know if you still facing this issue.

**Comment by osuleymanova** [comment] 2023-04-03 21:21
The issue is closed as not reproducible:
![Screenshot 2023-04-03 at 2 16 50 PM](https://user-images.githubusercontent.com/86437155/229629630-f112433f-dc81-40ef-b5ae-66dc5a7f9388.png)
It was probably a one-time system glitch.

**Closed by osuleymanova** 2023-04-03 21:21 UTC
