### ISSUE TITLE
Android Basics: first-kotlin-program

### ISSUE THREAD

**Issue by Mahmoud0ssama** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#100] opened 2021-10-05 11:04 UTC
The site of this link https://developer.android.com/training/kotlinplayground isn't working properly

**Comment by ashnohe** [comment] 2021-11-02 20:05
Hello @Mahmoud0ssama, thanks for reporting this issue.

The site appears to be working. May you please provide an error or a screenshot of the issue? Thanks!

**Comment by osuleymanova** [comment] 2022-08-02 21:26
@Mahmoud0ssama 
The issue is closed as no further clarification provided.

**Closed by osuleymanova** 2022-08-02 21:26 UTC
Labels: question
