### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by Brokynski** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#83] opened 2021-07-31 14:46 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-kotlin-birthday-message?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-one%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-kotlin-birthday-message#4

**In which task and step of the codelab can this issue be found?**
fun printCakeBottom

**Describe the problem**
missing:
     println() string necessary for first line of cake

Code found in module

fun printCakeBottom(age: Int, layers: Int) {
    repeat(layers) {
        repeat(age + 2) {
            print("@")
        }
        println()
    }    
}

There needs to be a println() string added before: repeat(layers)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by ashnohe** [comment] 2021-11-02 19:09
Duplicate of #119

**Closed by ashnohe** 2021-11-02 19:09 UTC
