### ISSUE TITLE
Android Basics: kotlin-birthday-message

### ISSUE THREAD

**Issue by ThomasRhoden** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#96] opened 2021-09-18 06:42 UTC
Erro na tradução.
![Captura de tela de 2021-09-18 03-41-14](https://user-images.githubusercontent.com/26886246/133879111-c65ecd89-e766-4ffd-837f-d11d61f95288.png)

**Comment by ashnohe** [comment] 2021-11-02 19:56
Duplicate of #88

**Closed by ashnohe** 2021-11-02 19:56 UTC
