### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by verg4ra** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#101] opened 2021-10-13 03:39 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-kotlin-birthday-message?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-one%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-kotlin-birthday-message#4

**In which task and step of the codelab can this issue be found?**
5. Create a cake with the layers and candles
    Create printCakeCandles()

**Describe the problem**
A step is missing in order for the code to look like the solution

1. Below the main() function and the printCakeTop() function, create a new function, printCakeCandles() that takes one argument, age, of type Int.
2. Inside, use a repeat() statement to print one comma , for the flame.

Missing step. Add a print statement to print one space for insetting the flames.
This step should go between the first and the second step

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by ashnohe** [comment] 2021-11-02 20:07
Duplicate of #119

**Closed by ashnohe** 2021-11-02 20:07 UTC
