### ISSUE TITLE
Android Basics: kotlin-birthday-message

### ISSUE THREAD

**Issue by wilfredomateo** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#71] opened 2021-07-12 01:16 UTC
There is currently a missing instruction to insert a **print (" ")** within the code for  "Create a cake with the layers and candles "

**Comment by ashnohe** [comment] 2021-11-02 18:43
Duplicate of #119

**Closed by ashnohe** 2021-11-02 18:43 UTC
