### ISSUE TITLE
Android Basics: first-kotlin-program

### ISSUE THREAD

**Issue by lucky4694-github** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#103] opened 2021-10-21 03:08 UTC
안녕하세요.
하단의 '뒤로', '다음' 버튼 때문에 본문의 내용 일부가 보이지 않습니다.
본문의 마지막 단락 아래 충분한 여백이 있었으면 좋겠습니다.

Hello
Because of the 'back' and 'next' buttons at the bottom, part of the text is not visible.
I hope there is enough space below the last paragraph of the text.

**Comment by ashnohe** [comment] 2021-11-02 20:11
Hi @lucky4694-github, thank you for reporting this issue. May you please provide a screenshot of the issue and a url to point us to the portion of the codelab you are working on?

Google Translate:
안녕하세요 @lucky4694-github, 이 문제를 보고해 주셔서 감사합니다. 문제의 스크린샷과 작업 중인 코드랩 부분을 가리키는 URL을 제공해 주시겠습니까?

**Comment by lucky4694-github** [comment] 2021-11-03 00:25
Thank you for answer.
This problem seems to be caused by the chrome screen being enlarged too much or the resolution of the laptop being low.
Forget about this issue.
I am very sorry to trouble you.

**Comment by ashnohe** [comment] 2021-11-03 15:41
Thanks @lucky4694-github for the additional details, appreciate it!

Triage notes:
This issue is potentially related to #84

**Comment by osuleymanova** [comment] 2023-04-03 20:58
The issue is closed as resolved.

**Closed by osuleymanova** 2023-04-03 20:58 UTC
