### ISSUE TITLE
Android Basics: first-kotlin-program

### ISSUE THREAD

**Issue by ArcySharky** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#144] opened 2021-11-13 04:46 UTC
The Kotlin Playground will not work in my browser with is Chrome and is up to date. I keeps giving an error.

**Comment by osuleymanova** [comment] 2022-08-01 18:43
The issue is closed as no further clarification provided.

**Closed by osuleymanova** 2022-08-01 18:43 UTC
