### ISSUE TITLE
Android Basics: first-template-project

### ISSUE THREAD

**Issue by gabriel-deluca** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#121] opened 2021-11-03 02:47 UTC
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x00007fdadeeb5267, pid=165357, tid=165630
#
# JRE version: OpenJDK Runtime Environment (11.0.10) (build 11.0.10+0-b96-7249189)
# Java VM: OpenJDK 64-Bit Server VM (11.0.10+0-b96-7249189, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libandroid_runtime.so+0x630267]
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: -Xms256m -Xmx1280m -XX:ReservedCodeCacheSize=512m -XX:+UseG1GC -XX:SoftRefLRUPolicyMSPerMB=50 -XX:CICompilerCount=2 -Dsun.io.useCanonCaches=false -Djdk.http.auth.tunneling.disabledSchemes="" -Djdk.attach.allowAttachSelf=true -Djdk.module.illegalAccess.silent=true -Dkotlinx.coroutines.debug=off -Djna.nosys=true -Djna.boot.library.path= -Didea.vendor.name=Google -Dsun.tools.attach.tmp.only=true -XX:ErrorFile=/home/gabriel/java_error_in_studio_%p.log -XX:HeapDumpPath=/home/gabriel/java_error_in_studio_.hprof -Didea.vendor.name=Google -Didea.paths.selector=AndroidStudio2020.3 -Djb.vmOptionsFile=/media/gabriel/BACKUP2021/Proyectos_Software/Android/android-studio-2020.3.1/android-studio/bin/studio64.vmoptions -Didea.platform.prefix=AndroidStudio -Didea.jre.check=true com.intellij.idea.Main

Host: AMD Phenom(tm) II X6 1100T Processor, 6 cores, 31G, MX 21 Wildflower
Time: Tue Nov  2 23:32:39 2021 -03 elapsed time: 72.766071 seconds (0d 0h 1m 12s)

---------------  T H R E A D  ---------------

Current thread (0x00007fdb0c941800):  JavaThread "Layoutlib Render Thread" daemon [_thread_in_native, id=165630, stack(0x00007fdaecd2b000,0x00007fdaece2c000)]

Stack: [0x00007fdaecd2b000,0x00007fdaece2c000],  sp=0x00007fdaece21098,  free space=984k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libandroid_runtime.so+0x630267]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  android.graphics.HardwareRenderer.nSyncAndDrawFrame(J[JI)I+0
j  android.graphics.HardwareRenderer.syncAndDrawFrame(Landroid/graphics/FrameInfo;)I+13
j  android.graphics.HardwareRenderer$FrameRenderRequest.syncAndDraw()I+8
j  com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(Landroid/view/ViewGroup;Landroid/graphics/HardwareRenderer;)Lcom/android/ide/common/rendering/api/Result;+18
j  com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(ZZ)Lcom/android/ide/common/rendering/api/Result;+522
j  com.android.layoutlib.bridge.impl.RenderSessionImpl.render(Z)Lcom/android/ide/common/rendering/api/Result;+3
j  com.android.layoutlib.bridge.BridgeRenderSession.render(JZ)Lcom/android/ide/common/rendering/api/Result;+49
j  com.android.ide.common.rendering.api.RenderSession.render(J)Lcom/android/ide/common/rendering/api/Result;+3
j  com.android.ide.common.rendering.api.RenderSession.render()Lcom/android/ide/common/rendering/api/Result;+4
j  com.android.tools.idea.rendering.RenderTask.lambda$renderInner$13(Lcom/intellij/psi/PsiFile;)Lcom/android/tools/idea/rendering/RenderResult;+4
j  com.android.tools.idea.rendering.RenderTask$$Lambda$3663.call()Ljava/lang/Object;+8
j  com.android.tools.idea.rendering.RenderExecutor$runAsyncActionWithTimeout$2.run()V+205
J 17601 c1 java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V java.base@11.0.10 (187 bytes) @ 0x00007fdbc29a7e04 [0x00007fdbc29a7000+0x0000000000000e04]
j  java.util.concurrent.ThreadPoolExecutor$Worker.run()V+5 java.base@11.0.10
j  java.lang.Thread.run()V+11 java.base@11.0.10
v  ~StubRoutines::call_stub

siginfo: si_signo: 4 (SIGILL), si_code: 2 (ILL_ILLOPN), si_addr: 0x00007fdadeeb5267

Register to memory mapping:

RAX=0x00007fdaece217c8 is pointing into the stack for thread: 0x00007fdb0c941800
RBX=0x00000000000003b4 is an unknown value
RCX=0x00000000000003b4 is an unknown value
RDX=0x00000000000001bb is an unknown value
RSP=0x00007fdaece21098 is pointing into the stack for thread: 0x00007fdb0c941800
RBP=0x00007fdadeeb33f0: <offset 0x000000000062e3f0> in /media/gabriel/BACKUP2021/Proyectos_Software/Android/android-studio-2020.3.1/android-studio/plugins/android/resources/layoutlib/data/linux/lib64/libandroid_runtime.so at 0x00007fdade885000
RSI=0x00007fdaece21a90 is pointing into the stack for thread: 0x00007fdb0c941800
RDI=0x0 is NULL
R8 =0x00007fdbe4cc0410 points into unknown readable memory: 0xffffffffffffffff | ff ff ff ff ff ff ff ff
R9 =0x00007fdadeec01a0: <offset 0x000000000063b1a0> in /media/gabriel/BACKUP2021/Proyectos_Software/Android/android-studio-2020.3.1/android-studio/plugins/android/resources/layoutlib/data/linux/lib64/libandroid_runtime.so at 0x00007fdade885000
R10=0x000000007fffffff is an unknown value
R11=0x0000000080000001 is an unknown value
R12=0x00000000000001bb is an unknown value
R13=0x00007fdaece21a68 is pointing into the stack for thread: 0x00007fdb0c941800
R14=0x00000000000001bb is an unknown value
R15=0x00000000000001d0 is an unknown value

Registers:
RAX=0x00007fdaece217c8, RBX=0x00000000000003b4, RCX=0x00000000000003b4, RDX=0x00000000000001bb
RSP=0x00007fdaece21098, RBP=0x00007fdadeeb33f0, RSI=0x00007fdaece21a90, RDI=0x0000000000000000
R8 =0x00007fdbe4cc0410, R9 =0x00007fdadeec01a0, R10=0x000000007fffffff, R11=0x0000000080000001
R12=0x00000000000001bb, R13=0x00007fdaece21a68, R14=0x00000000000001bb, R15=0x00000000000001d0
RIP=0x00007fdadeeb5267, EFLAGS=0x0000000000010246, CSGSFS=0x002b000000000033, ERR=0x0000000000000000
  TRAPNO=0x0000000000000006

Top of Stack: (sp=0x00007fdaece21098)
0x00007fdaece21098:   00007fdadeec0225 00007fdaece22678
0x00007fdaece210a8:   00000000000001bf 00000000000003cf
0x00007fdaece210b8:   00007fdaece217d8 00007fdaece21100
0x00007fdaece210c8:   00007fdaece21880 00007fdaece21218 

Metaspace:

Usage:
  Non-class:    235.15 MB capacity,   230.63 MB ( 98%) used,     3.73 MB (  2%) free+waste,   800.12 KB ( <1%) overhead. 
      Class:     37.35 MB capacity,    34.47 MB ( 92%) used,     2.52 MB (  7%) free+waste,   375.94 KB ( <1%) overhead. 
       Both:    272.50 MB capacity,   265.10 MB ( 97%) used,     6.25 MB (  2%) free+waste,     1.15 MB ( <1%) overhead. 

Virtual space:
  Non-class space:      238.00 MB reserved,     236.36 MB (>99%) committed 
      Class space:        1.00 GB reserved,      37.47 MB (  4%) committed 
             Both:        1.23 GB reserved,     273.84 MB ( 22%) committed 

Chunk freelists:
   Non-Class:  1.10 MB
       Class:  23.00 KB
        Both:  1.13 MB

MaxMetaspaceSize: unlimited
CompressedClassSpaceSize: 1.00 GB

CodeHeap 'non-profiled nmethods': size=259300Kb used=16027Kb max_used=16027Kb free=243272Kb
 bounds [0x00007fdbd07f9000, 0x00007fdbd17c9000, 0x00007fdbe0532000]
CodeHeap 'profiled nmethods': size=259296Kb used=58546Kb max_used=58720Kb free=200750Kb
 bounds [0x00007fdbc0ac1000, 0x00007fdbc4481000, 0x00007fdbd07f9000]
CodeHeap 'non-nmethods': size=5692Kb used=1983Kb max_used=2008Kb free=3708Kb
 bounds [0x00007fdbc0532000, 0x00007fdbc07a2000, 0x00007fdbc0ac1000]
 total_blobs=32099 nmethods=30274 adapters=1733
 compilation: enabled
              stopped_count=0, restarted_count=0
 full_count=0

VM Arguments:
jvm_args: -Xms256m -Xmx1280m -XX:ReservedCodeCacheSize=512m -XX:+UseG1GC -XX:SoftRefLRUPolicyMSPerMB=50 -XX:CICompilerCount=2 -Dsun.io.useCanonCaches=false -Djdk.http.auth.tunneling.disabledSchemes="" -Djdk.attach.allowAttachSelf=true -Djdk.module.illegalAccess.silent=true -Dkotlinx.coroutines.debug=off -Djna.nosys=true -Djna.boot.library.path= -Didea.vendor.name=Google -Dsun.tools.attach.tmp.only=true -XX:ErrorFile=/home/gabriel/java_error_in_studio_%p.log -XX:HeapDumpPath=/home/gabriel/java_error_in_studio_.hprof -Didea.vendor.name=Google -Didea.paths.selector=AndroidStudio2020.3 -Djb.vmOptionsFile=/media/gabriel/BACKUP2021/Proyectos_Software/Android/android-studio-2020.3.1/android-studio/bin/studio64.vmoptions -Didea.platform.prefix=AndroidStudio -Didea.jre.check=true 
java_command: com.intellij.idea.Main
java_class_path (initial): /media/gabriel/BACKUP2021/Proyectos_Software/Android/android-studio-2020.3.1/android-studio/lib/bootstrap.jar:/media/gabriel/BACKUP2021/Proyectos_Software/Android/android-studio-2020.3.1/android-studio/lib/extensions.jar:/media/gabriel/BACKUP2021/Proyectos_Software/Android/android-studio-2020.3.1/android-studio/lib/util.jar:/media/gabriel/BACKUP2021/Proyectos_Software/Android/android-studio-2020.3.1/android-studio/lib/jdom.jar:/media/gabriel/BACKUP2021/Proyectos_Software/Android/android-studio-2020.3.1/android-studio/lib/log4j.jar:/media/gabriel/BACKUP2021/Proyectos_Software/Android/android-studio-2020.3.1/android-studio/lib/jna.jar:/media/gabriel/BACKUP2021/Proyectos_Software/Android/android-studio-2020.3.1/android-studio/jre/lib/tools.jar
Launcher Type: SUN_STANDARD

[Global flags]
     intx CICompilerCount                          = 2                                         {product} {command line}
     uint ConcGCThreads                            = 2                                         {product} {ergonomic}
    ccstr ErrorFile                                = /home/gabriel/java_error_in_studio_%p.log            {product} {command line}
     uint G1ConcRefinementThreads                  = 6                                         {product} {ergonomic}
   size_t G1HeapRegionSize                         = 1048576                                   {product} {ergonomic}
    uintx GCDrainStackTargetSize                   = 64                                        {product} {ergonomic}
    ccstr HeapDumpPath                             = /home/gabriel/java_error_in_studio_.hprof         {manageable} {command line}
   size_t InitialHeapSize                          = 268435456                                 {product} {command line}
   size_t MarkStackSize                            = 4194304                                   {product} {ergonomic}
   size_t MaxHeapSize                              = 1342177280                                {product} {command line}
   size_t MaxNewSize                               = 805306368                                 {product} {ergonomic}
   size_t MinHeapDeltaBytes                        = 1048576                                   {product} {ergonomic}
    uintx NonNMethodCodeHeapSize                   = 5825164                                {pd product} {ergonomic}
    uintx NonProfiledCodeHeapSize                  = 265522874                              {pd product} {ergonomic}
    uintx ProfiledCodeHeapSize                     = 265522874                              {pd product} {ergonomic}
    uintx ReservedCodeCacheSize                    = 536870912                              {pd product} {command line}
     bool SegmentedCodeCache                       = true                                      {product} {ergonomic}
     intx SoftRefLRUPolicyMSPerMB                  = 50                                        {product} {command line}
     bool UseCompressedClassPointers               = true                                 {lp64_product} {ergonomic}
     bool UseCompressedOops                        = true                                 {lp64_product} {ergonomic}
     bool UseG1GC                                  = true                                      {product} {command line}

Logging:
Log output configuration:
 #0: stdout all=warning uptime,level,tags
 #1: stderr all=off uptime,level,tags

Environment Variables:
PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
SHELL=/bin/bash
DISPLAY=:0
LANG=es_AR.UTF-8

Signal Handlers:
SIGSEGV: [libjvm.so+0xc2dd80], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
SIGBUS: [libjvm.so+0xc2dd80], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
SIGFPE: [libjvm.so+0xc2dd80], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
SIGPIPE: SIG_IGN, sa_mask[0]=00000000000010000000000000000000, sa_flags=SA_RESTART
SIGXFSZ: [libjvm.so+0xa839f0], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
SIGILL: [libjvm.so+0xc2dd80], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
SIGUSR2: [libjvm.so+0xa840d0], sa_mask[0]=00000000000000000000000000000000, sa_flags=SA_RESTART|SA_SIGINFO
SIGHUP: [libjvm.so+0xa80ac0], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
SIGINT: [libjvm.so+0xa80ac0], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
SIGTERM: [libjvm.so+0xa80ac0], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
SIGQUIT: [libjvm.so+0xa80ac0], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO

---------------  S Y S T E M  ---------------

OS:PRETTY_NAME="MX 21 Wildflower"
DISTRIB_ID=MX
DISTRIB_RELEASE=21
DISTRIB_CODENAME="Wildflower"
DISTRIB_DESCRIPTION="MX 21 Wildflower"
uname:Linux 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64
OS uptime: 0 days 15:26 hours
libc:glibc 2.31 NPTL 2.31 
rlimit (soft/hard): STACK 8192k/infinity , CORE 0k/infinity , NPROC 127712/127712 , NOFILE 4096/4096 , AS infinity/infinity , CPU infinity/infinity , DATA infinity/infinity , FSIZE infinity/infinity , MEMLOCK 64k/64k
load average:4.23 2.55 1.84

/proc/meminfo:
MemTotal:       32842932 kB
MemFree:          378640 kB
MemAvailable:   26825000 kB
Buffers:         1786240 kB
Cached:         22333720 kB
SwapCached:            0 kB
Active:          6969044 kB
Inactive:       22065144 kB
Active(anon):       5368 kB
Inactive(anon):  4987588 kB
Active(file):    6963676 kB
Inactive(file): 17077556 kB
Unevictable:       17068 kB
Mlocked:           17068 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               284 kB
Writeback:             0 kB
AnonPages:       4816572 kB
Mapped:           905016 kB
Shmem:             71084 kB
KReclaimable:    2869956 kB
Slab:            3033820 kB
SReclaimable:    2869956 kB
SUnreclaim:       163864 kB
KernelStack:       16368 kB
PageTables:        42464 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    16421464 kB
Committed_AS:    9504388 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       38796 kB
VmallocChunk:          0 kB
Percpu:             2720 kB
HardwareCorrupted:     0 kB
AnonHugePages:   1849344 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
FileHugePages:         0 kB
FilePmdMapped:         0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:      770732 kB
DirectMap2M:    25403392 kB
DirectMap1G:     7340032 kB

/sys/kernel/mm/transparent_hugepage/enabled:
[always] madvise never
/sys/kernel/mm/transparent_hugepage/defrag (defrag/compaction efforts parameter):
always defer defer+madvise [madvise] never

/proc/sys/kernel/threads-max (system-wide limit on the number of threads):
255424
/proc/sys/vm/max_map_count (maximum number of memory map areas a process may have):
65530
/proc/sys/kernel/pid_max (system-wide limit on number of process identifiers):
4194304

Steal ticks since vm start: 0
Steal ticks percentage since vm start:  0.000

CPU:total 6 (initial active 6) (6 cores per cpu, 1 threads per core) family 16 model 10 stepping 0 microcode 0x10000dc, cmov, cx8, fxsr, mmx, sse, sse2, sse3, popcnt, mmxext, 3dnowpref, lzcnt, sse4a, tsc, tscinvbit, tscinv
CPU Model and flags from /proc/cpuinfo:
model name	: AMD Phenom(tm) II X6 1100T Processor
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt nodeid_msr cpb hw_pstate vmmcall npt lbrv svm_lock nrip_save pausefilter
Online cpus:
0-5
Offline cpus:
6-7
BIOS frequency limitation:
<Not Available>
Frequency switch latency (ns):
<Not Available>
Available cpu frequencies:
<Not Available>
Current governor:
<Not Available>
Core performance/turbo boost:
<Not Available>

Memory: 4k page, physical 32842932k(378640k free), swap 0k(0k free)

vm_info: OpenJDK 64-Bit Server VM (11.0.10+0-b96-7249189) for linux-amd64 JRE (11.0.10+0-b96-7249189), built on Mar 31 2021 19:21:57 by "androidbuild" with gcc Android (6875598, based on r399163b) Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315dfbea7c137aa2e6d362dbb457e388158d)

END.

**Comment by ashnohe** [comment] 2021-11-03 15:37
Hi @gabriel-deluca, thanks for raising this issue. May you please provide a description of what portion of the codelab you were working on to lead to the crash?

**Comment by osuleymanova** [comment] 2022-08-01 18:41
@gabriel-deluca 
The issue is closed as no further clarification provided.

**Closed by osuleymanova** 2022-08-01 18:41 UTC
Labels: question
