### ISSUE TITLE
Android Basics: Done button missing - birthday-card-app

### ISSUE THREAD

**Issue by GellieColtRu** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#2] opened 2020-10-18 09:55 UTC
**URL of codelab**

**In which task and step of the codelab can this issue be found?**
Android Basics: Build a basic layout
create a Birthday Card app

**Describe the problem**

Following the tutorials step by step, when I finish all steps, and arrive at number 7 "learn more" when click on done it does not take me to the next pathway, it returns me to the welcome to codelabs page.. and it doesn't save my progress.. the pathways before this one works just fine.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by ashnohe** [comment] 2021-11-01 21:13
Duplicate of #1

**Closed by ashnohe** 2021-11-01 21:13 UTC
Labels: Formatting issue on DAC
