### ISSUE TITLE
Android Basics: first-kotlin-program

### ISSUE THREAD

**Issue by MarcoAHBorja** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#157] opened 2021-11-14 04:48 UTC
Hi everyone.

I request your help to clarify the error when executing a program in kotlin using "Playground" "the link is: https://developer.android.com/training/kotlinplayground" when I execute the program it sends the following error message:
Exception in thread "main" java.io.FileNotFoundException: /var/task/tmp/276797285949427e8863914ab0ab3a08/executor.policy (No such file or directory)
  at java.io.FileOutputStream.open0 (FileOutputStream.java:-2)
  at java.io.FileOutputStream.open (FileOutputStream.java:270)
  at java.io.FileOutputStream. <init> (FileOutputStream.java:213)
  the content of the program is:

This is the code
fun main () {
     println ("Hello, world!")
}

Thank you for all your help.

**Comment by osuleymanova** [comment] 2022-08-01 18:08
Duplicate of #154, #153, #152

**Comment by osuleymanova** [comment] 2023-04-03 21:20
The issue is closed as not reproducible:
![Screenshot 2023-04-03 at 2 16 50 PM](https://user-images.githubusercontent.com/86437155/229629630-f112433f-dc81-40ef-b5ae-66dc5a7f9388.png)
It was probably a one-time system glitch.

**Closed by osuleymanova** 2023-04-03 21:20 UTC
